spring.application.name=Api-Gateway

server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# AUTH
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# CIUDADANOS
spring.cloud.gateway.routes[1].id=ciudadano-service
spring.cloud.gateway.routes[1].uri=lb://CIUDADANO-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/ciudadanos/**

# ELECCIONES
spring.cloud.gateway.routes[2].id=elecciones-service
spring.cloud.gateway.routes[2].uri=lb://ELECCIONES-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/elecciones/**

# CANDIDATOS
spring.cloud.gateway.routes[3].id=candidatos-service
spring.cloud.gateway.routes[3].uri=lb://CANDIDATOS-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/candidatos/**

# VOTACIONES
spring.cloud.gateway.routes[4].id=votacion-service
spring.cloud.gateway.routes[4].uri=lb://VOTACION-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/votaciones/**

# RESULTADOS
spring.cloud.gateway.routes[5].id=resultados-service
spring.cloud.gateway.routes[5].uri=lb://RESULTADOS-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/resultados/**

# AUDITORIA
spring.cloud.gateway.routes[6].id=auditoria-service
spring.cloud.gateway.routes[6].uri=lb://AUDITORIA-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/auditoria/**

#CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true